import express from 'express'; import Database from 'better-sqlite3'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'node:crypto'; import path from 'node:path'; import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)), app=express(), db=new Database(path.join(root,'jumper.sqlite')); const SECRET=process.env.JUMPER_SECRET||'dev-only-change-me';
db.pragma('journal_mode = WAL'); db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS progress(user_id TEXT PRIMARY KEY,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));`);
app.use(express.json()); app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff'); next()});
const cookie=(res,id)=>res.cookie('jumper_session',jwt.sign({sub:id},SECRET,{expiresIn:'30d'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2592e6});
function auth(req,res,next){const raw=(req.headers.cookie||'').split(';').find(x=>x.trim().startsWith('jumper_session='))?.split('=')[1]; try{req.user=jwt.verify(raw,SECRET); next()}catch{res.status(401).json({error:{code:'unauthorized',message:'Sign in required'}})}}
const defaultState={city:0,level:0,pad:0,aura:0,coins:0,score:0,landings:0,unlockedMax:0,ownedShoes:['basic'],shoe:'basic',flipMode:'front',stats:{attempts:0,perfectLandings:0}};
const ensureProgress=(userId)=>db.prepare('INSERT OR IGNORE INTO progress(user_id,state,version,updated_at) VALUES (?,?,?,?)').run(userId,JSON.stringify(defaultState),0,new Date().toISOString());
app.post('/api/auth/register',(req,res)=>{const {email,password}=req.body||{}; if(typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<8)return res.status(422).json({error:{code:'validation_error',message:'Use a valid email and an 8+ character password'}}); try{const id=crypto.randomUUID(); db.prepare('INSERT INTO users(id,email,password_hash,created_at) VALUES (?,?,?,?)').run(id,email.toLowerCase(),bcrypt.hashSync(password,12),new Date().toISOString()); ensureProgress(id); cookie(res,id); res.status(201).json({data:{email}})}catch{res.status(409).json({error:{code:'email_taken',message:'That email is already registered'}})}});
app.post('/api/auth/login',(req,res)=>{const row=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body?.email||'').toLowerCase()); if(!row||!bcrypt.compareSync(String(req.body?.password||''),row.password_hash))return res.status(401).json({error:{code:'invalid_credentials',message:'Email or password is incorrect'}}); ensureProgress(row.id); cookie(res,row.id); res.json({data:{email:row.email}})});
app.post('/api/auth/logout',(req,res)=>res.clearCookie('jumper_session').status(204).end());
app.get('/api/auth/me',auth,(req,res)=>{const u=db.prepare('SELECT email FROM users WHERE id=?').get(req.user.sub);res.json({data:u})});
app.get('/api/progress',auth,(req,res)=>{ensureProgress(req.user.sub); const row=db.prepare('SELECT state,version,updated_at FROM progress WHERE user_id=?').get(req.user.sub);res.json({data:{state:JSON.parse(row.state),version:row.version,updatedAt:row.updated_at}})});
app.put('/api/progress',auth,(req,res)=>{const {state,version}=req.body||{}; if(!state||typeof version!=='number'||version<0||version>1e9)return res.status(422).json({error:{code:'validation_error',message:'Invalid progress payload'}}); const safe={...defaultState,...state,aura:Math.max(-1000000,Math.min(1000000,Number(state.aura)||0)),coins:Math.max(0,Number(state.coins)||0),score:Math.max(0,Number(state.score)||0)}; const result=db.prepare('UPDATE progress SET state=?,version=version+1,updated_at=? WHERE user_id=? AND version=?').run(JSON.stringify(safe),new Date().toISOString(),req.user.sub,version); if(!result.changes)return res.status(409).json({error:{code:'stale_state',message:'Progress changed elsewhere; reload required'}}); res.json({data:{state:safe,version:version+1}})});
const dist=path.join(root,'..','dist'); app.use(express.static(dist)); app.get(/.*/,(req,res)=>res.sendFile(path.join(dist,'index.html'))); app.listen(process.env.PORT||3000,()=>console.log('Jumper server listening on http://localhost:'+(process.env.PORT||3000)));
