import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import type {Phase,Progress} from './types';
import {CITIES,SHOES} from './game/levels';
import {auraTier,computeTrajectory,landingReward,launch,missPenalty,nextPad,people,reviveCost,shoe} from './game/engine';
import {api} from './api';

const fresh:Progress={city:0,level:0,pad:0,aura:0,coins:0,score:0,landings:0,unlockedMax:0,ownedShoes:['basic'],shoe:'basic',flipMode:'front',stats:{attempts:0,perfectLandings:0}};

function Auth({onLogin}:{onLogin:()=>void}){const [mode,setMode]=useState<'login'|'register'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');async function go(e:React.FormEvent){e.preventDefault();try{await(mode==='login'?api.login(email,password):api.register(email,password));onLogin()}catch(e){setError((e as Error).message)}}return <main className="auth"><div className="brand-mark">J</div><p className="eyebrow">A CITY-SCALE FLIGHT GAME</p><h1>Find your line.<br/><em>Stick the landing.</em></h1><p className="muted">Charge your jump, spin through the skyline, and build a crowd that follows your run.</p><form onSubmit={go}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary">{mode==='login'?'Enter the city':'Create runner'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New runner? Create an account':'Already have an account? Sign in'}</button></main>}

function Game({onLogout}:{onLogout:()=>void}){
 const [p,setP]=useState<Progress>(fresh),[version,setVersion]=useState(0),[phase,setPhase]=useState<Phase>('wait'),[power,setPower]=useState(0),[powerDir,setPowerDir]=useState(1),[spinning,setSpinning]=useState(false),[flips,setFlips]=useState(0),[message,setMessage]=useState('Press and hold SPACE to charge');
 const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),flipsRef=useRef(0),flightResolved=useRef(false),versionRef=useRef(0),player=useRef({x:50,y:320,vx:0,vy:0,angle:0});
 const currentLevel=()=>CITIES[p.city].levels[p.level];
 const place=(state:Progress)=>{const level=CITIES[state.city].levels[state.level];if(state.pad===0){player.current.x=level.start[0];player.current.y=level.start[1]-80}else{const pad=level.pads[state.pad-1];player.current.x=pad[0]+(pad[2]-40)/2;player.current.y=pad[1]-80}player.current.vx=0;player.current.vy=0;player.current.angle=0};
 useEffect(()=>{api.progress().then(x=>{setP(x.state);setVersion(x.version);versionRef.current=x.version;place(x.state)}).catch(onLogout)},[]);
 const save=(next:Progress)=>{setP(next);const expected=versionRef.current;versionRef.current+=1;api.save(next,expected).then(x=>{versionRef.current=x.version;setVersion(x.version)}).catch(()=>{versionRef.current=expected;setMessage('Save conflict — reload to keep the latest run')})};
 const resetRun=(next:Progress)=>{flipsRef.current=0;setFlips(0);setSpinning(false);place(next);setPhase('wait');setPower(0);setPowerDir(1)};
 const release=()=>{if(phase!=='sit')return;const v=launch(power,p);flightResolved.current=false;player.current.vx=v.vx;player.current.vy=v.vy;setPhase('fly');setMessage('Press SPACE in the air to spin')};
 const advance=()=>{if(phase==='win'){const n={...fresh,aura:p.aura,coins:p.coins,ownedShoes:p.ownedShoes,shoe:p.shoe,unlockedMax:p.unlockedMax};save(n);resetRun(n);return}const n=nextPad(p);save(n);resetRun(n);setMessage(n.city!==p.city?`New city unlocked: ${CITIES[n.city].name}`:'Press and hold SPACE to charge')};
 const startCharge=()=>{if(phase==='wait'){setPower(0);setPowerDir(1);setPhase('sit');setMessage('Release SPACE to jump')}else if(phase==='fly'){setSpinning(true)}else if(phase==='land'||phase==='city_clear'){advance()}else if(phase==='dead'||phase==='win'){if(phase==='dead'){const n={...p,level:0,pad:0,score:0};save(n);resetRun(n)}else advance()}};
 const toggleFlip=()=>{if(phase!=='wait'&&phase!=='sit')return;const next={...p,flipMode:p.flipMode==='front'?'back':'front'};save(next);setMessage(`Flip direction: ${next.flipMode==='back'?'BACK':'FRONT'} (F)`)};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.code==='KeyF'&&!e.repeat){e.preventDefault();toggleFlip();return}if(e.code!=='Space'||e.repeat)return;e.preventDefault();startCharge()};const up=(e:KeyboardEvent)=>{if(e.code!=='Space')return;e.preventDefault();if(phase==='sit')release();if(phase==='fly')setSpinning(false)};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[phase,p,power]);
 useEffect(()=>{if(phase!=='sit')return;const id=setInterval(()=>setPower(x=>{let next=x+2.5*powerDir;if(next>100){setPowerDir(-1);next=100}if(next<0){setPowerDir(1);next=0}return next}),1000/60);return()=>clearInterval(id)},[phase,powerDir]);
 useEffect(()=>{if(phase!=='fly')return;const id=setInterval(()=>{if(flightResolved.current)return;const q=player.current,prevFeet=q.y+80;q.x+=q.vx;q.y+=q.vy;q.vy+=.4;if(spinning){const direction=p.flipMode==='back'?-1:1;q.angle-=direction*shoe(p).spin*Math.PI/180;flipsRef.current+=shoe(p).spin/360;setFlips(Math.floor(flipsRef.current))}const pad=currentLevel().pads[p.pad];const feet=q.y+80;const center=q.x+20;const top=q.vy>0&&prevFeet<=pad[1]+1&&feet>=pad[1]&&feet<=pad[1]+20&&center>=pad[0]&&center<=pad[0]+pad[2];if(top){flightResolved.current=true;q.y=pad[1]-80;q.vy=0;const upright=Math.abs(q.angle%(Math.PI*2))<.7||Math.abs(Math.abs(q.angle%(Math.PI*2))-Math.PI*2)<.7;if(upright){const r=landingReward(p,Math.floor(flipsRef.current));const n={...p,score:p.score+r.score,aura:r.aura,coins:p.coins+r.coins,landings:p.landings+1,stats:{...p.stats,perfectLandings:p.stats.perfectLandings+1}};save(n);setFlips(Math.floor(flipsRef.current));setSpinning(false);const finalLevel=p.level===4,finalCity=p.city===CITIES.length-1;setPhase(finalLevel?(finalCity?'win':'city_clear'):'land');setMessage(`Clean landing +${r.score} score · +${r.coins} coins`)}else{const n={...p,aura:missPenalty(p,.5),stats:{...p.stats,attempts:p.stats.attempts+1}};save(n);setPhase('dead');setMessage('You landed tilted. The city remembers.')}}else if(q.y>600||q.x>850){flightResolved.current=true;const n={...p,aura:missPenalty(p),stats:{...p.stats,attempts:p.stats.attempts+1}};save(n);setPhase('dead');setMessage('Missed the line. The city remembers.')}},1000/60);return()=>clearInterval(id)},[phase,p,spinning]);
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d')!;function draw(){const W=c.width,H=c.height,level=currentLevel(),night=!!level.night;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,night?'#10153a':'#9bd8ed');g.addColorStop(1,night?'#20244f':'#e5b58b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle=night?'#31395c':'#7fa57f';ctx.fillRect(0,H-48,W,48);for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#243a63':'#304d78';ctx.fillRect(i*170+30,H-48-(i%3)*60,100,48+(i%3)*60)}ctx.fillStyle='#765b4c';ctx.fillRect(level.start[0],level.start[1],60,H-level.start[1]);ctx.fillStyle='#a98a6d';ctx.fillRect(level.start[0],level.start[1],60,10);level.pads.forEach((pad,i)=>{ctx.fillStyle='#667084';ctx.fillRect(pad[0],pad[1],pad[2],H-pad[1]);ctx.fillStyle=i<p.pad?'#5be0b0':i===p.pad?'#ffcc62':'#6c718b';ctx.fillRect(pad[0],pad[1],pad[2],10)});const q=player.current;if(phase==='sit'){const v=launch(power,p),dots=computeTrajectory(q.x+20,q.y+40,v.vx,v.vy);dots.forEach((dot,i)=>{if(dot.x<0||dot.x>800||dot.y<0||dot.y>600)return;ctx.fillStyle=`rgba(255,255,255,${Math.max(.24,1-i*.035)})`;ctx.beginPath();ctx.arc(dot.x,dot.y,i<3?4:3,0,Math.PI*2);ctx.fill()})}ctx.save();ctx.translate(q.x+20,q.y+40);ctx.rotate(q.angle);ctx.fillStyle=shoe(p).color;ctx.beginPath();ctx.arc(0,-27,12,0,7);ctx.fill();ctx.fillRect(-10,-15,20,28);ctx.fillStyle='#25294a';ctx.fillRect(-9,13,7,28);ctx.fillRect(3,13,7,28);ctx.fillStyle='#fff';ctx.fillRect(-7,33,5,3);ctx.fillRect(5,33,5,3);ctx.restore();raf.current=requestAnimationFrame(draw)}draw();return()=>cancelAnimationFrame(raf.current)},[p,phase,power]);
 const buy=(id:string)=>{const s=SHOES.find(x=>x.id===id)!;if(p.coins>=s.price&&!p.ownedShoes.includes(id))save({...p,coins:p.coins-s.price,ownedShoes:[...p.ownedShoes,id]})};
 return <main className="game"><header><div><p className="eyebrow">JUMPER / {CITIES[p.city].name.toUpperCase()}</p><h2>{currentLevel().name}</h2></div><div className="top-actions"><span className="pill">◉ {p.coins.toLocaleString()}</span><button className="ghost" onClick={onLogout}>Sign out</button></div></header><section className="stats"><div><small>AURA</small><strong>{p.aura.toLocaleString()}</strong><span>{auraTier(p.aura)} · {people(p.aura).toLocaleString()} people</span></div><div><small>SCORE</small><strong>{p.score.toLocaleString()}</strong><span>{p.landings} clean landings</span></div><div><small>PROGRESS</small><strong>{p.city+1}<i>/6</i></strong><span>Stage {p.level+1} of 5</span></div></section><div className="arena"><canvas ref={canvas} width="800" height="500"/><div className="arena-label"><span>{CITIES[p.city].name} · {p.flipMode==='back'?'BACKFLIP':'FRONTFLIP'} (F)</span><b>{message}</b></div>{phase==='sit'&&<div className="power"><div style={{width:`${power}%`}}/></div>}<button className="jump" aria-label="Space control" tabIndex={-1}>{phase==='sit'?`${Math.round(power)}%`:'SPACE'}</button>{phase==='dead'&&<div className="modal"><b>RUN OVER</b><p>{message}</p><button className="primary" disabled={p.coins<reviveCost(p)} onClick={()=>{const n={...p,coins:p.coins-reviveCost(p)};save(n);resetRun(n)}}>Revive · {reviveCost(p)} coins</button><button className="link" onClick={()=>{const n={...p,level:0,pad:0,score:0};save(n);resetRun(n)}}>Restart city</button></div>}{(phase==='land'||phase==='city_clear'||phase==='win')&&<div className="modal success"><b>{phase==='win'?'YOU CLEARED THE RUN':phase==='city_clear'?'CITY CLEARED':'PERFECT LANDING'}</b><p>{message}</p><button className="primary" onClick={advance}>{phase==='win'?'Play again':phase==='city_clear'?'Continue':'Next pad'}</button></div>}</div><section className="lower"><div><p className="eyebrow">EQUIPMENT</p><div className="shoes">{SHOES.map(s=><button className={p.shoe===s.id?'shoe active':'shoe'} key={s.id} onClick={()=>p.ownedShoes.includes(s.id)?save({...p,shoe:s.id}):buy(s.id)}><i style={{background:s.color}}/><b>{s.name}</b><span>{p.ownedShoes.includes(s.id)?(p.shoe===s.id?'EQUIPPED':'Equip'):`${s.price} coins`}</span></button>)}</div></div><div className="tip"><p className="eyebrow">THE FEEL</p><b>SPACE is the whole run.<br/>F switches front / back.</b><span>Hold SPACE to charge, release to fly, and press it again in the air to spin.</span></div></section></main>
}

function App(){const [user,setUser]=useState<boolean|null>(null);useEffect(()=>{api.me().then(()=>setUser(true)).catch(()=>setUser(false))},[]);if(user===null)return <div className="loading">Loading the city…</div>;return user?<Game onLogout={()=>{api.logout();setUser(false)}}/>:<Auth onLogin={()=>setUser(true)}/>}
createRoot(document.getElementById('root')!).render(<App/>);
